### ISSUE TITLE
import multi_tau_lags error

### ISSUE THREAD

**Issue by rheadric** [NSLS-II-CHX/CHX_BugReport#14] opened 2016-10-17 01:40 UTC
In order to illustrate the error, I made a new notebook with only a single input, as shown below. The problem seems to be with multi_tau_lags.  Has it been replaced?

from chxanalys.chx_libs import (np, roi, time, datetime, os, get_events, 

```
                            getpass, db, get_images,LogNorm, plt,tqdm, utils, Model,

                           multi_tau_lags)
```

/opt/conda_envs/analysis-2016-09-30/lib/python3.5/site-packages/filestore/retrieve.py:15: UserWarning: Do not import filestore.retrieve, import filestore.api instead
  warnings.warn("Do not import filestore.retrieve, "
/opt/conda_envs/analysis-2016-09-30/lib/python3.5/site-packages/IPython/html.py:14: ShimWarning: The `IPython.html` package has been deprecated. You should import from `notebook` instead. `IPython.html.widgets` has moved to `ipywidgets`.
  "`IPython.html.widgets` has moved to `ipywidgets`.", ShimWarning)

---

ImportError                               Traceback (most recent call last)
<ipython-input-1-76ad7d1799c4> in <module>()
----> 1 from chxanalys.chx_libs import (np, roi, time, datetime, os, get_events, 
      2                                 getpass, db, get_images,LogNorm, plt,tqdm, utils, Model,
      3                                multi_tau_lags)

ImportError: cannot import name 'multi_tau_lags'

**Comment by rheadric** [comment] 2016-10-17 05:50
This works on the old server at https://notebook-backup.nsls2.bnl.gov/

**Comment by yugangzhang** [comment] 2016-10-17 16:26
I update the code on the new sever https://notebook-backup.nsls2.bnl.gov/  and it should work now.

But, the new sever is not stable, please use the old sever https://notebook-backup.nsls2.bnl.gov and we will let you know when the new sever is ready to use.

**Comment by yugangzhang** [comment] 2016-11-17 14:52
Can we close it?

**Comment by rheadric** [comment] 2016-12-31 16:53
Sorry to keep this open for so long.  But I've run into a similar issue in chxanalys.XPCS_SAXS.  


ImportError                               Traceback (most recent call last)
<ipython-input-2-4d678bc7c09b> in <module>()
     10 
     11 
---> 12 from chxanalys.XPCS_SAXS import (get_circular_average,save_lists,get_ring_mask, get_each_ring_mean_intensity,
     13                                  plot_qIq_with_ROI,save_saxs_g2,plot_saxs_g2,fit_saxs_g2,cal_g2,
     14                                 create_hot_pixel_mask,get_circular_average,get_t_iq,save_saxs_g2,

ImportError: cannot import name 'save_saxs_g2'

**Comment by yugangzhang** [comment] 2016-12-31 17:32
i am updating the code and it will work in a week. Thanks for your patience!

**Comment by yugangzhang** [comment] 2017-01-03 03:28
@rheadric 
I finished updating the codes and pipelines and copy the latest pipeline "XPCS_XSVS_SAXS_GiSAXS_Single_2017_V0.ipynb" in your folder. This pipeline works both for saxs and gisaxs scattering geometry. There are clear comments in the pipeline to guide you how to control. Basically, you can set   scat_geometry = 'gi_saxs'  in the cell just below the bold fonts "Control Runs Here"  for gisaxs scattering.  You also might need to change the mask file path, beam center ( inc_x0, inc_y0, refl_x0, refl_y0), and all the q-set parameters, such as qstart, qend, qnumber, et.al. Once, you set up all the parameters, you can simply press the button "run all" in 'Cell' Tab.

**Comment by rheadric** [comment] 2017-01-04 05:36
Thanks for making the update and for making the new pipeline.  I'm using a copy of it, "XPCS_XSVS_SAXS_GiSAXS_Single_2017_V0_Sam4_Graphene_No1_4th_scan_a1e0fb.ipynb" in order to try and reproduce analysis that I have already completed with the old pipeline.  

The first issue that I ran into was that I need bins=4. I've added this capability back in from the old pipeline, including recalculating timeperframe and Nimg.  This seems to work -- so far, so good.

The second issue is that I'm not sure if I need the line "bp.to_csv('/XF11ID/analysis/Commissioning/eiger4M_badpixel.csv', mode='a'  )". It gives an error since I don't have permission for that path, so I have ignored the error.

The third issue is that after entering the incident beam and reflected beam positions ( inc_x0, inc_y0, refl_x0, refl_y0), the alphai angle is calculated as 0.000208935737318, which is incorrect. It should be about 0.2 degrees.

Fourth issue is that I can't find the section "Create X boxes along Y qz line to generate X*Y ROIs".  There seems to be no place to input the qstart, qend, q_num parameters for the dynamic analysis.  I was also using  the "Create one box to inspect the reflect beam" capability which also seems to be missing. I could copy these from the old pipeline, but I am not sure if that is the right thing to do, or possibly you intended something else?

**Comment by yugangzhang** [comment] 2017-01-04 20:40
@rheadric 
1) You don't need the "bp.to_csv('/XF11ID/analysis/Commissioning/eiger4M_badpixel.csv', mode='a' )". line and you can simply comment this line out.

2) You are right the  alphai angle should be about 0.2 degrees. Please the cell 
python ```check Ldet = md['detector_distance'] *1000     # detector to sample distance (mm)``` and Ldet should be ~ 4889 in unit of mm. If it is 4889,000 then you don't need to do "*1000". I guess that we put this number sometime in mm and sometime in m.

3) For define XPCS ROI, there is a cell 
python ```
if scat_geometry =='gi_saxs':
    # Define Q-ROI
    #* Users provide the interested Qz and Qr here for XPCS analysis, e.g., qr start/end/number/width et.al
    # Change these lines

    qz_start = 0.025
    qz_end = 0.04
    qz_num= 3
    gap_qz_num = 1
    
    qz_width = (qz_end - qz_start)/(qz_num +gap_qz_num)
    qr_start =  0.0025
    qr_end = 0.07
    qr_num = 14
    gap_qr_num = 5
    qr_width = ( qr_end- qr_start)/(qr_num+gap_qr_num)

    Qr = [qr_start , qr_end, qr_width, qr_num]
    Qz=  [qz_start,   qz_end,  qz_width , qz_num ]
    # Don't Change these lines below here
    roi_mask, qval_dict = get_gisaxs_roi( Qr, Qz, qr_map, qz_map, mask= mask )
``` and you can define the qstart, qend, q_num parameters.

For  "Create one box to inspect the reflect beam", there is cell called 
python 
```if scat_geometry =='gi_saxs':
    ### Change the below lines to if define another ROI, if define even more, just repeat this process
    define_second_roi = True #False  #if True to define another line; else: make it False
    if define_second_roi:    
        qval_dict1 = qval_dict.copy()
        roi_mask1 = roi_mask.copy()
        del qval_dict, roi_mask
    ## The Second ROI
    if define_second_roi: ...
```. Then, you can make qz_num2 =1 and qr_num2 =1 to define one that sort of inspection box.

**Comment by rheadric** [comment] 2017-01-05 04:19
I've got it mainly working now.  The part that is missing is the Static Analysis.   Can you add the static analysis back into the pipeline?  I've tried to do it, but there are some variables undefined so it doesn't work yet.
 

**In particular the sections and cells:**


## Get 1D Curve (Q||-intensity¶)
* Users put cuts here for static analysis

...

boxes_qr = label_array_qzr  
box_maskr_qr = boxes_qr*maskr

qr_1d = get_1d_qr( avg_imgr, Qr, Qz, qr, qz, inc_x0,  None,  True, ticks, .8,
                  save= True, setup_pargs=setup_pargs )

## get qr as a function of time

qr_t = get_t_qrc( FD, time_edge, Qr, Qz, qr, qz)

plot_t_qrc( qr_t, time_edge, pargs=setup_pargs, xlim = [0,0.08], ylim=[1e-2, 100.0])

**Some of the variables like "qr" and "qz" seem to have changed their names, and others like "maskr" are no longer  in the pipeline at all.**

**Comment by yugangzhang** [comment] 2017-01-06 00:59
@rheadric  I updated the code and add the 
python ```
elif scat_geometry =='gi_saxs':
    Nimg = FD.end - FD.beg 
    time_edge = create_time_slice( N= Nimg, slice_num= 3, slice_width= 1, edges = None )
    time_edge =  np.array( time_edge ) + good_start
    print( time_edge )    
    qrt_pds = get_t_qrc( FD, time_edge, Qr, Qz, qr_map, qz_map, path=data_dir, uid = uidstr )    
    plot_qrt_pds( qrt_pds, time_edge, qz_index = 0, uid = uidstr, path =  data_dir )
```
to the notebook.

I also copied the latest pipeline called XPCS_XSVS_SAXS_GiSAXS_Single_2017_V0_20170105.ipynb  to your folder.

**Comment by rheadric** [comment] 2017-01-06 05:07
There may be something missing. Here is the error output after I ran XPCS_XSVS_SAXS_GiSAXS_Single_2017_V0_20170105.ipynb down to the changed cell:

```
[[  5   6]
 [ 51  52]
 [ 99 100]]

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-36-d578ac524a56> in <module>()
     15     print( time_edge )
     16 
---> 17     qpt, iqst, qt = get_t_qrc( FD, time_edge, mask, pargs=setup_pargs, nx=1500 )
     18     plot_t_iqc( qt, iqst, time_edge, pargs=setup_pargs, xlim=[qt.min(), qt.max()],
     19            ylim = [iqst.min(), iqst.max()], save=True )

TypeError: get_t_qrc() missing 3 required positional arguments: 'Qz', 'qr', and 'qz'
```

 I noticed that XPCS_XSVS_SAXS_GiSAXS_Single_2017_V0_20170105.ipynb does not have the same changed code as you listed above.  I copied the code listed above into XPCS_XSVS_SAXS_GiSAXS_Single_2017_V0_Sam4_Graphene_No1_4th_scan_a1e0fb and it is working. 

However, one additional problem is that this is working on the dynamic "cuts" whereas previously we had a  section for the static cuts with its own separate definition of qz_start, qz_end, qz_num, etc.  I really want to have a completely separate static analysis as we were doing before because I normally cover a wider range of qr in the static analysis. Should we add that back in?

You can see in XPCS_XSVS_SAXS_GiSAXS_Single_2017_V0_Sam4_Graphene_No1_4th_scan_a1e0fb that I have added the headings. 
 

## Static Analysis

### To do: add the static analysis.
 
I will try to add it on my own, for my "...Sam4_Graphene..." analysis, but I suggest that you may want to have it in the generic pipeline as well.

**Comment by yugangzhang** [comment] 2017-01-06 17:06
@rheadric I added all the static analysis feature to the latest pipeline, which I copied to your folder as XPCS_XSVS_SAXS_GiSAXS_Single_2017_V0_20170106.ipynb .
The main update:
1) Add back the roi for static analysis
2) Add the "Make a Profile Plot", basically a binned waterfall analysis. 
3) Correct a bug in PDF report, and now it can create pdf and attach to the olog book

**Comment by rheadric** [comment] 2017-01-07 05:31
XPCS_XSVS_SAXS_GiSAXS_Single_2017_V0_20170106.ipynb still gives the same error as the 20170105 version.  In fact all four of the changes listed above seem to be missing as well. Maybe copied over the wrong file??

**Comment by yugangzhang** [comment] 2017-01-07 16:00
You are right. For some reason, it was not successfully copied. I copied again with filename as XPCS_XSVS_SAXS_GiSAXS_Single_2017_V0_20170106_2.ipynb. I checked the copied pipeline and it is the latest one.

**Comment by rheadric** [comment] 2017-01-08 05:24
It works now all the way to the XPCS Analysis Report.  The report looks really good, but I have some suggestions on how to make it more useful.

**XPCS Analysis Report — issues and improvements.**
XPCS_Analysis_Report_for_uid=a1e0fb_1.pdf

**1. Metadata**
- “Reflect Center” is missing. Can add it to metadata?

**2. Static Analysis**
- Does not show any analysis, only the average intensity image.
- Would like to have static "ROI on Image".
- Binned waterfall plot (Profile Plot) should be in this section.
- Would like to have qr-time from a1e0fb_qrt_pds.csv plot included.  Best would be to have 1 version on linear scale and a second version on log-log scale.

**3. Define ROI**
- Should call this heading “Define Dynamic ROI” to distinguish from static analysis.

**4. Time -  dependent Plot**
- It shows the binned waterfall plot.  Would like to have the regular (unbinned) waterfall plot here.
- Reflected beam intensity (second ROI) dominates over other intensities.  It would be better to separate first and second Q-ROIs into two different plots.

**5. One Time Correlation Function** 
- g2 fit plot: This is too small.  It deserves a whole page to itself.
- Q-rate fit plot.  The reflected beam dominates the plot. Suggest to add axis range parameter to “plot_q_rate_fit_general”.

**6. Two Time Correlation Function**
- Would like to show at least one plot at each qz, but not necessarily all 48 plots, which would be too much for the summary. Is there a way to control this?

**Comment by rheadric** [comment] 2017-01-08 06:15
Error while analyzing a new scan...
XPCS_XSVS_SAXS_GiSAXS_Single_2017_V0_20170106_2_Sam4_Graphene_No1_2nd_scan_8edf62

The problem is during the binning step.   Error output is below.

```
ValueError                                Traceback (most recent call last)
<ipython-input-35-59c23c3e8533> in <module>()
      6 mask, avg_img, imgsum, bad_frame_list = compress_eigerdata(imgs, mask, md, filename, 
      7          force_compress= force_compress,  para_compress= para_compress,  bad_pixel_threshold= 1e14,
----> 8                         bins=bin_frame_number, num_sub= 100, num_max_para_process= 500  )
      9 min_inten = 10
     10 good_start = max(good_start, np.where( np.array(imgsum) > min_inten )[0][0] )

/opt/conda_envs/analysis/lib/python3.5/site-packages/chxanalys-0+untagged.207.gcad1d75.dirty-py3.5.egg/chxanalys/chx_compress.py in compress_eigerdata(images, mask, md, filename, force_compress, bad_pixel_threshold, bad_pixel_low_threshold, hot_pixel_threshold, nobytes, bins, bad_frame_list, para_compress, num_sub, dtypes, reverse, num_max_para_process)
     85                                     bad_pixel_low_threshold=bad_pixel_low_threshold,nobytes= nobytes, bins=bins,
     86                                      num_sub=num_sub, dtypes=dtypes, reverse=reverse,
---> 87                                               num_max_para_process=num_max_para_process)
     88             else:
     89                 return init_compress_eigerdata( images, mask, md, filename, 

/opt/conda_envs/analysis/lib/python3.5/site-packages/chxanalys-0+untagged.207.gcad1d75.dirty-py3.5.egg/chxanalys/chx_compress.py in para_compress_eigerdata(images, mask, md, filename, num_sub, bad_pixel_threshold, hot_pixel_threshold, bad_pixel_low_threshold, nobytes, bins, dtypes, reverse, num_max_para_process, cpu_core_number)
    165     for i in range( Nf ):
    166         mask_, avg_img_, imgsum_, bad_frame_list_ = res_[i]
--> 167         imgsum[i*num_sub: (i+1)*num_sub] = imgsum_
    168         bad_frame_list[i*num_sub: (i+1)*num_sub] = bad_frame_list_
    169         if i==0:

ValueError: could not broadcast input array from shape (62) into shape (250)
```

**Comment by yugangzhang** [comment] 2017-01-08 23:24
@rheadric Your new problem "The problem is during the binning step. Error output is below." is  really a bug. I will take it as a first priority. Thanks for your suggestions for the PDF, but it's more or less a customized request, and I will keep it in mind.

**Comment by yugangzhang** [comment] 2017-01-09 15:13
@rheadric I fixed the bug related to compress of frames with bins. I also add the "good_end" option in get_bad_frame_list function to get bad frame list in a better way. Actually, you also can change the FD.end = good_end to define a new FD.end.  I made all the changes in the new pipeline XPCS_XSVS_SAXS_GiSAXS_Single_2017_V0_20170110.ipynb  in your folder.

**Comment by rheadric** [comment] 2017-01-11 06:58
I'm not sure yet if this is a bug, but it appears to be a very serious issue with the mult-tau calculation.

g2 curves exhibit a very strong oscillation that mimics the oscillation of the reflected beam.  However, one-time from two-time doesn't show the oscillation (except for the ROI on the reflected beam).  This appears to be a normalizatiion problem with multitau.  But it seems to indicate that the total intensity of the whole frame is somehow being used for the g2 normalization??  This seems very unlikely!

Also, It is not clear to me why the reflected beam g2 should show the oscillation if we are normalizing frame-by-frame.   How is the normalization being done?

Pipeline is: XPCS_XSVS_SAXS_GiSAXS_Single_2017_V0_20170110__Sam10_Graphene_No3_1st_scan_160c81.ipynb

The results summary is in Results/XPCS_Analysis_Report_for_uid=160c81_1.pdf

Also we can compare to a nearly identical analysis of the same scan done on 12/25/2016.  In that analysis, there is no strong oscilation and multitau matches the one-time from two-time fairly well.  See XPCS_GiSAXS_Single_Run_Oct_Sam10_Graphene_No3_1st_scan_160c81_V2

I wonder what could have changed since 12/25, possibly in one of the recent updates?

**Comment by yugangzhang** [comment] 2017-01-11 15:17
You are right that the total intensity of the whole frame was used for the g2 normalization in your XPCS_XSVS_SAXS_GiSAXS_Single_2017_V0_20170110__Sam10_Graphene_No3_1st_scan_160c81.ipynb. We found that this kind of normalization was useful for SAXS.

You can disable this normalization by doing the following. At the very begining of the pipeline, there is a control cell,
Please make use_imgsum_norm=False  #if True use imgsum to normalize intensity for one-time calculatoin (currently, it's True).

**Comment by rheadric** [comment] 2017-01-11 15:24
OK, thanks!  Once that is done, will we be normalizing frame-by-frame?  Or by some other method?  And in some cases, where there is no kinetics, we may want to normalize by the total intensity.  But in that case we should mask out the reflected beam, right?  Would that work, i.e. would it remove the artifact cause by the intensity oscillation of the reflected beam?

**Comment by yugangzhang** [comment] 2017-01-11 15:38
1) if make make use_imgsum_norm=True,  g2(q, tau) = <   [ I(q, t1) /I(t1)_total_frame]  *  [ I(q, t1+tau) /I(t1+tau)_total_frame] > / ( <   [ I(q, t1) /I(t1)_total_frame]  >*<  [ I(q, t1+tau) /I(t1+tau)_total_frame]  > )
if make use_imgsum_norm=False,  g2(q, tau) = <   I(q, t1)  *  I(q, t1+tau) > / ( <   I(q, t1)  >*<  I(q, t1+tau)  > ) 

2) I think that if you calculate the frame total intensity by masking out the reflected beam, you should remove that artifact caused by the intensity oscillation of the reflected beam.

**Closed** 2017-01-15 07:24 UTC
